authenticator:
  type: in_memory
  in_memory:
    allowed_users:
      user: "password"
      john: "doe"
      jane: "doe"

credentials:
  type: in_memory
  in_memory:
    user_sources:
      user:
        type: in_memory
      john:
        type: in_memory
      jane:
        type: in_memory